[workspace]
resolver = "3"
members = ["critic", "critic-shared", "critic-server", "critic-components"]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

